Vagrant.configure("2") do |config|
	# Server
  common = <<-SHELL
  yum install -y kubectl
  yum install -y net-tools
  sudo curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" sh -
  sed -i '$ d' /etc/systemd/system/k3s.service
  echo -e "\t--flannel-iface 'eth1'" | tee -a /etc/systemd/system/k3s.service
  sudo systemctl daemon-reload
  sudo systemctl restart k3s
  SHELL
  config.vm.box = "centos/8"
  config.vm.box_url = "centos/8"

	config.vm.define "server" do |controle|
    controle.vm.hostname = "Server"
    controle.vm.network "private_network", ip: "192.168.42.110"
    controle.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--cpus", "2"]
      v.customize ["modifyvm", :id, "--memory", "4096"]
      v.customize ["modifyvm", :id, "--name", "server"]
    end
    config.vm.provision :shell, :inline => common
    controle.vm.provision "file", source: "app1.yaml", destination: "app1.yaml"
    controle.vm.provision "file", source: "app2.yaml", destination: "app2.yaml"
    controle.vm.provision "file", source: "app3.yaml", destination: "app3.yaml"
    controle.vm.provision "file", source: "service.yaml", destination: "service.yaml"
    controle.vm.provision "file", source: "ingress.yaml", destination: "ingress.yaml"
    controle.vm.provision "shell", path: "run.sh"
  end
end
