Vagrant.configure("2") do |config|
  #Master Server
  common = <<-SHELL
  sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config    
  sudo systemctl restart sshd
  sudo yum install -y net-tools
  SHELL
  config.vm.box = "centos/8"
  config.vm.box_url = "centos/8"
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/masterkey"
  config.vm.provision "shell", inline: "cat /home/vagrant/.ssh/masterkey >> /home/vagrant/.ssh/authorized_keys"
  
	config.vm.define "mmounchiS" do |controle|
    controle.vm.hostname = "mmounchiS"
    controle.vm.network "private_network", ip: "192.168.42.110"
    controle.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--cpus", "1"]
      v.customize ["modifyvm", :id, "--memory", "1024"]
      v.customize ["modifyvm", :id, "--name", "mmounchiS"]
    end
    config.vm.provision :shell, :inline => common
    controle.vm.provision "shell", path: "install_master.sh"
    config.trigger.after :up do |trigger|
      trigger.run = {inline: 'bash -c "vagrant ssh -c \"sudo cat /var/lib/rancher/k3s/server/node-token\" mmounchiS > ~/test.txt"'}
    end
  end
  #Slave Server
  config.vm.define "del-aljSW" do |control|
    control.vm.hostname = "del-aljSW"
    control.vm.network "private_network", ip: "192.168.42.111"
    control.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--cpus", "1"]
      v.customize ["modifyvm", :id, "--memory", "1024"]
      v.customize ["modifyvm", :id, "--name", "del-aljSW"]
    end
    config.vm.provision :shell, :inline => common
    control.vm.provision "file", source: "~/test.txt", destination: "token.txt"
    control.vm.provision "shell", path: "install_worker.sh" , run: "always"
  end
end
