Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.box_url = "debian/buster64"
	config.vm.define "mmounchiS" do |mmounchi|
    mmounchi.vm.hostname = "mmounchiS"
    mmounchi.vm.network "public_network", bridge: "en0: Ethernet"
    mmounchi.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--cpus", "3"]
      v.customize ["modifyvm", :id, "--memory", "3584"]
      v.customize ["modifyvm", :id, "--name", "mmounchiS"]
    end
  end
end

#10.12.100.167